### ISSUE TITLE
Invalid info about bitbucket and dropbox account 

### ISSUE THREAD

**Issue by jkspentester** [D4Vinci/Cr3dOv3r#10]
The python codes checks and give login successful to bitbucket and dropbox even user never created and account on bitbucket and the password is not same on the dropbox as give while running the script but it still shows that the login is successful.

**Comment by jkspentester** [comment]
to reproduce this i used the same email but entered different passwords while scanning and it still shows that login successful for bitbucket and dropbox so something is broken maybe please check

**Comment by D4Vinci** [comment]
Fixing it thank you

**Comment by D4Vinci** [comment]
Released a hotfix check it out and reopen please if the problem stays!
