### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by lplume** [D4Vinci/Cr3dOv3r#13]
i would suggest you two useful alternatives:
* instead of open and fill the login form, just POST the form action url
* if available, prefer and act as a mobile request, often mobile version are way easier

keep on improving this tool, would be nice to have the leaks without popping out a web browser

regards

**Comment by D4Vinci** [comment]
Thank you for the ideas but for the first idea not all the websites I can post to it !
Some websites action url randomly generated for every session so the page have to be loaded.
