### ISSUE TITLE
Leaked password?

### ISSUE THREAD

**Issue by madaratech** [D4Vinci/Cr3dOv3r#14]
```
Now you give it this email's old or leaked password then it checks this credentials against 16 websites (ex: facebook, twitter, google...) then it tells you if login successful in any website!
```
Thanks for doing this, but have a quick question for you.

As you said to provide the old password, but hacked-email API only provides the email is leaked or not, not the password, so how we can get the password to submit for check-ups with other services?

**Comment by D4Vinci** [comment]
No hacked-emails provide leak link if it exists and any way you have the leak name so you can search about it
