### ISSUE TITLE
failed to import mechanicalsoup as ms

### ISSUE THREAD

**Issue by micr0be** [D4Vinci/Cr3dOv3r#29]
When I download the requirements it downloads beautifulsoup4 instead of mechanicalsoup 0.9.
I'm guessing the import needs to be renamed to account for the update of mechanicalsoup to beautifulsoup.

p.s i tried swapping the names in the import modules and it didn't work, so it's not that straightforward. 

so basically the script doesn't load for me at all until this is fixed.

**Comment by D4Vinci** [comment]
WTF!!

**Comment by micr0be** [comment]
Am I doing something wrong? I'm using Kali
