### ISSUE TITLE
Instagram login is a false positive

### ISSUE THREAD

**Issue by MansoorMajeed** [D4Vinci/Cr3dOv3r#33]
On a wrong password, the script says the instagram password is `successful`.

```
#Now let's check if it was success by trying to use the same form again and if I could use it then the login not success
	try:
		browser.select_form(form2)
		browser.close()
		return "{2} -[{1}{3} {0} {4}{2}] Login unsuccessful!{4}".format(name,R,W,Bold,end)
	except:
		browser.close()
		return "{2} -[{1}{3} {0} {4}{2}] Login successful !{4}".format(name,G,W,Bold,end)
```

I think this is the part where the issue is.

**Comment by upgoingstar** [comment]
Same goes for Linkedin. That's also a false positive. If I get some time this weekend, I will try to send a pull request.

**Comment by h3ct0rjs** [comment]
Confirmed @MansoorMajeed  Instagram is  a false positive, the if you don't  enter a password it will mark instagram as sucessful

**Comment by D4Vinci** [comment]
Started to work on the new update, wait for it very soon

**Comment by h3ct0rjs** [comment]
cool, please send us a message to be beta testers.

**Comment by D4Vinci** [comment]
Instagram removed and version 0.3 released check it out and please reopen the issue if their's still an issue

**Comment by h3ct0rjs** [comment]
Hi @D4Vinci can you reference the commit that solves the problem, it seems that you're 
trying to get the len size of a data type bool. 

Check this Core/ispwned.py", line 41 
>  Final_text   = "\n(GG)Results from haveibeenpwned website (W): (Y)"+str(len(data))

**Comment by D4Vinci** [comment]
This variable should not be bool this error may appear because haveibeenpwned blocked you after many tries with their rate limiting
Maybe I will make haveibeenpwned runs from command line argument to avoid block after 3-4 uses :3

**Comment by D4Vinci** [comment]
Released a hotfix now check it out and please respond if there's any problem remaining

**Comment by h3ct0rjs** [comment]
Hi @D4Vinci please try to reference the hotfix with the commit id, is more helpful to find the changes that you did. 

It seems okay to me, but in the last version it didn't try to make a test against instagram. 

Regards, 
Hector F.
