### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by morganh83** [D4Vinci/Cr3dOv3r#38]
I've used the Windows, Kali, Ubuntu 16.04, and Docker setup methods and using Python 2 and 3. I always get the same error:

`[+] Checking email in public leaks...
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 139, in <module>
    main()
  File "Cr3d0v3r.py", line 99, in main
    if ispwned.check_hackedEmails(email):
  File "/Cr3dOv3r/Core/ispwned.py", line 9, in check_hackedEmails
    res = req.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
Am I missing something?

**Comment by VFPAP** [comment]
Same issue here...

**Comment by D4Vinci** [comment]
Yeah, that's because hacked-emails website just started to use Cloudflare today!
You can use the "-p" option till I figure out a solution.

**Comment by D4Vinci** [comment]
Now waiting for reply from the company

**Comment by n13lo** [comment]
hi all
I was preparing this report now.
but I already know the problem.
Thank you

hola a todos.
yo estaba preparando este reporte ahora.
pero ya conozco el problema .
Gracias
https://asciinema.org/a/zPF0qOj11Up3vJ0mtPcGG91nn

**Comment by CosasDePuma** [comment]
I have the same issue and now it is time to wait for an update, meanwhile...

@n13lo, no veo ningun contacto hacia tu usuario (email o semejante), asi que te lo pregunto por aqui. Que tema de zsh usas? Me gustó mucho verlo en tu asciinema.

**Comment by johnlockejrr** [comment]
Problem with Cloudflare on hacked-emails.com

https://github.com/johnlockejrr/Cr3dOv3r/blob/master/Core/ispwned.py

```
#Added cfscrape method to bypass Cloudflare on hacked-emails.com - johnlockejrr
def check_hackedEmails(email,return_what=""):
    #from hacked-emails API docs from https://hacked-emails.com/api_docs
    url = "https://hacked-emails.com/api?q="+str(email)
    scraper = cfscrape.create_scraper()
    req = scraper.get(url).json()
    res = req
    if res["status"]=="found":
        if return_what=="":
            return True
        else:
            return res
    else:
        return False
```

**Comment by D4Vinci** [comment]
No need, they just fixed the problem and I tested it now and it's working fine.
reopen if there's any problem remaining :smile:
