### ISSUE TITLE
json related error.

### ISSUE THREAD

**Issue by MickeyAl** [D4Vinci/Cr3dOv3r#44]
Hi all,

i am facing this json error 
![image](https://user-images.githubusercontent.com/34653271/38620574-6f249a8a-3da7-11e8-9a8f-546cb36bf653.png)

i got the same error on linux, windows & docker.
please assist.

**Comment by hugo4715** [comment]
Exact same error here :c

**Comment by D4Vinci** [comment]
The new version will be realeased soon as a whole new framework so every thing is rewritten :smile:

**Comment by D4Vinci** [comment]
I just checked, this from hacked-emails website not from me.
Talking to the admin already

**Comment by D4Vinci** [comment]
Duplicate of #46
See my answer there
