### ISSUE TITLE
Newline error

### ISSUE THREAD

**Issue by Bobpick** [D4Vinci/Cr3dOv3r#55]
When I run " python2.7 Cr3d0v3r.py <my@emailaccount.com>" I get

bash: syntax error near unexpected token `newline'

Any suggestion?

**Comment by axelarator** [comment]
`python2.7 Cr3d0v3r.py -q my@emailaccount.com`

Just forgot to add the -q argument

**Comment by D4Vinci** [comment]
try putting the email between quotations and which os are you using?

**Comment by D4Vinci** [comment]
Quotations should fix it.
