### ISSUE TITLE
[+] Plaintext passwords found! Error

### ISSUE THREAD

**Issue by csenger18** [D4Vinci/Cr3dOv3r#57]
used python version: python2.7
error message: [+] Plaintext passwords found!
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 123, in <module>
    main()
  File "Cr3d0v3r.py", line 99, in main
    ispwned.parse_data(email,args.np)
  File "/root/Cr3d0v3r/Core/ispwned.py", line 41, in parse_data
    print(C+" │"+B+"  └──── "+W+pp.split(":")[1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
thanks for help

**Comment by D4Vinci** [comment]
Just released the new version with the fix at the same time as the issue! check it out :smile:

**Comment by csenger18** [comment]
Ok thanks sorry. :)

**Comment by csenger18** [comment]
ok I updated used with  python3 and now?
raceback (most recent call last):
  File "Cr3d0v3r.py", line 5, in <module>
    import mechanicalsoup as ms
ModuleNotFoundError: No module named 'mechanicalsoup'

**Comment by csenger18** [comment]
hmm intresting worked with python 2.7 

tahnks for the update :+1:

**Comment by D4Vinci** [comment]
just install the requirements for python 3 !!
