### ISSUE TITLE
Unicode Crash - Windows

### ISSUE THREAD

**Issue by SillySam** [D4Vinci/Cr3dOv3r#65]
When getting password input, after submiting it (pressing `ENTER`) Python itself crashes. This is due to a conflict with the `win_unicode_console` library.
I was able to run `win_unicode_console.disable()` before the input which prevented the crash but I don't notice a difference with this lib disabled (is it really needed).

(Also created a [PR](https://github.com/D4Vinci/Cr3dOv3r/pull/64) to fix banner encoding issue for Windows users)

Environment: Windows 10, Python 3.7

**Comment by D4Vinci** [comment]
I will look at this when it's possible and respond to you.
Thanks for help :smile:

**Comment by D4Vinci** [comment]
yup, win_unicode_console is needed for windows to make colors shows.
As no one else is facing the same problem, I think the problem might be with python version you are using.
Try running it with version 3.6 or anything older and write me here if the problem persists.
Till then I will close the issue.
