### ISSUE TITLE
banners. ubuntu

### ISSUE THREAD

**Issue by mayday77** [D4Vinci/Cr3dOv3r#67]
Hello , Master!
Here is a problem.

----------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "Cr3d0v3r.py", line 123, in <module>
    main()
  File "Cr3d0v3r.py", line 96, in main
    banner()
  File "/home/xxx/Downloads/Cr3dOv3r/Core/utils.py", line 22, in banner
    banner = open(os.path.join("Data","banners.txt"), encoding="utf8").read()
TypeError: 'encoding' is an invalid keyword argument for this function
------------------------------------------------------------------------------------------------------------------------

was fixed by add next lines : 

import sys, codecs
	banner = codecs.open(os.path.join("Data","banners.txt"), encoding="utf8").read()
----------------------------------------------------------------------------------------------------

But! Still CAN'T type password

help!

**Comment by D4Vinci** [comment]
Encoding problem is already fixed before just do ```git pull``` and the password is hidden that's why you don't see it !!
