### ISSUE TITLE
Tool didn't find plain text password

### ISSUE THREAD

**Issue by taher-it** [D4Vinci/Cr3dOv3r#75]
Hi, The issue is when I search for an email the tool couldn't find the plain text of the password. any thoughts.

![image](https://user-images.githubusercontent.com/9547879/50425703-19562e00-088d-11e9-9d67-6de9287ccc98.png)

**Comment by tbalz2319** [comment]
Yes I have been having this same issue . It used to work this past summer . I thought the problem was in my end

**Comment by D4Vinci** [comment]
yup, it's a problem with the site, they changed their policy.
I already talked to them.
