### ISSUE TITLE
[ Google   ] Login successful! Always.

### ISSUE THREAD

**Issue by ayYZmpZGyVLg** [D4Vinci/Cr3dOv3r#77]
I checked it and its wrong password.

Edit: i think it might be special case, when password : qwerty its successful.

**Comment by D4Vinci** [comment]
There would a hole new version soon that I will rewrite the tool in it to fix all problems and add some new features :smile:
I will start in coding it when you finish my current project I work on so I can focus so wait for it very soon!

**Comment by ayYZmpZGyVLg** [comment]
Cant wait 😄

**Comment by pretech86** [comment]
me too have the same problem
