### ISSUE TITLE
Issues with login requests

### ISSUE THREAD

**Issue by kongwenbin** [D4Vinci/Cr3dOv3r#8]
When checking whether an old password still works with the various popular websites listed, the results from the login requests were incorrect. 

For instance, I entered `Cr3dOv3r` as my password, which was incorrect. However, I still received `Login successful !` for services such as Vimeo, Dropbox, Bitbucket and Mediafire.

![issue](https://user-images.githubusercontent.com/3257054/32787859-9cd864c2-c992-11e7-9474-7304beec7c36.png)

**Comment by D4Vinci** [comment]
The problem is with this websites form data but I will fix it ASAP
Till fix I will close this issue as known

**Comment by D4Vinci** [comment]
Released a hotfix check it out and reopen please if the problem stays!

**Comment by kongwenbin** [comment]
I have checked out the hotfix already, the issue has been fixed and the tool is working like magic now 👍 
very nice and useful tool there @D4Vinci !
